# Utilise l'image de base nginx version 1.21.1
FROM nginx:1.21.1

# Ajoute une étiquette avec les informations du mainteneur
LABEL maintainer="Serigne Babacar WADE"

# Met à jour les paquets et installe curl et git
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y curl && \
    apt-get install -y git

# Supprime le contenu du répertoire /usr/share/nginx/html/
RUN rm -Rf /usr/share/nginx/html/*

# Clone le contenu du dépôt Git "static-website-example" dans /usr/share/nginx/html/
RUN git clone https://github.com/diranetafen/static-website-example.git /usr/share/nginx/html

# Définit la commande à exécuter lorsque le conteneur démarre : lance nginx en mode daemon
CMD nginx -g 'daemon off;'
